apiVersion: v1
kind: Service
metadata:
  name: result-app-svc
  labels:
    name: result-app-svc
    app: demo-voting-app
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
  selector:
    name: result-app-pod
    app: demo-voting-app