apiVersion: v1
kind: Service
metadata:
  name: voting-app-svc
  labels:
    name: voting-app-svc
    app: demo-voting-app
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
  selector:
    name: voting-app-pod
    app: demo-voting-app