apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        name: myapp-pod
        app: myapp
        type: pod

    spec:
      containers:
      - name: nginx-image
        image: nginx
  replicas: 3
  selector:
    matchLabels:
      app: myapp
